development:
  encoding: utf8
  adapter: postgresql
  database: soapbox_development
  host: 127.0.0.1
  min_messages: warning

test:
  encoding: utf8
  adapter: postgresql
  database: soapbox_test
  host: 127.0.0.1
  min_messages: warning

production:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

# test:
#  adapter: sqlite3
#  database: db/test.sqlite3
#  pool: 5
#  timeout: 5000
